spring:
  application:
  name: spring-boot-redis

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
  redis:
    # 连接超时时间（毫秒）
    timeout: 3000
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # 集群地址配法 和 spring.redis.host 2选1
#    cluster:
#      nodes: 10.8.4.165:6379,10.8.4.165:6380,10.8.4.165:6381,10.8.4.165:6379,10.8.4.165:6380,10.8.4.165:6381
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 4

#################redis哨兵设置#################
# Redis服务器master的名字
#spring.redis.sentinel.master=master8026
# redis-sentinel的配置地址和端口
#spring.redis.sentinel.nodes=10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378