server:
  port: 8080

spring:
  datasource:
    username: dev
    password: 123456
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 1000
      max-idle: 8
      min-idle: 4
    timeout: 3000


mybatis:
  mapper-locations: classpath:mapper/*-Mapper.xml
#  type-aliases-package: com.ade.exp.mybatis.entity

#showSql
logging:
  level:
    com:
      ade:
        exp:
          mybatis:
            mapper: debug

